### PR TITLE
Reduce allocations

### PR DESCRIPTION
**Pull request by clipperhouse**
Remove second return parameter `suffixRunes` from many functions, as it’s not used by every caller, and requires an allocation. In many cases, just its length is needed, so use `utf8.RuneCountInString`. In cases where `suffixRunes` is needed, create it locally.

Before:

```
Benchmark_Stem-8   	      50950417 ns/op	   4.41 MB/s	38536284 B/op	 2066112 allocs/op
```

After:

```
Benchmark_Stem-8   	      25477538 ns/op	   8.82 MB/s	 1377490 B/op	   58406 allocs/op
```

~2x throughput improvement and ~30x allocation reduction.

(nit: my formatter seems to have removed a bunch of blank `//` lines; not deliberate by me, let me know if it matters.)

### CODE REVIEW

**Comment by kljensen** [comment]
Thanks so much! I'll take a look shortly.

**Comment by clipperhouse** [comment]
Great! I suspect the failures above have to do with old Go versions. I updated go.mod and test.yml for Go 1.19 and above (and got rid of the cache), let’s see if that fixes it.

(If you’re not ready to update Go version, that’s fine, but at least we’ll have some troubleshooting.)

**Comment by clipperhouse** [comment]
Looks good over here: https://github.com/clipperhouse/snowball/actions

**Comment by kljensen** [comment]
Thanks @clipperhouse. Three quick questions. (I haven't looked at this code in a while, so apologies if these are non-sensical.)

1. It seems like there were a lot of white space changes. Can you help me understand those?
2. How do you feel about using `suffixLength` or `suffixLen` instead of `sLen` throughout?
3. I like your benchmark above. Is there a way to incorporate that into the automated tests?

**Comment by clipperhouse** [comment]
Cheers @kljensen 

1) I didn’t do any intentional whitespace changes, but the Go formatter seemed to. In particular it removed a lot of empty `//` comment lines. [Here’s some explanation](https://www.perplexity.ai/search/in-golang-with-vs-code-and-gop-yEvFndSLTMasBuPXJ9GA6A). On GitHub, you can “Hide whitespace changes” in the PR, under the little settings wheel icon at the top. I can go through and try to undo those formats if it’s important.
2) Done!
3) We could change the test.yml action to `go test ./... -benchmem -bench=.`, which will run (log) the benchmarks in addition to the tests. In terms of doing anything with benchmark results, like tracking over time, I don’t know a good way to do that. I’m sure something exists.

**Comment by kljensen** [comment]
Super. I suspect I'll squash merge. Would you add yourself to the list of contributors?

**Comment by clipperhouse** [comment]
Done (I assume you mean contributors in the README?) and thanks! I usually squash PRs as well.

**Comment by kljensen** [comment]
Thanks @clipperhouse merged and released v0.10.0

**Pull request merged**
